Update workflow_test.yml

diff --git a/.github/workflows/workflow_test.yml b/.github/workflows/workflow_test.yml
--- a/.github/workflows/workflow_test.yml
+++ b/.github/workflows/workflow_test.yml
@@ -1,56 +1,66 @@
-name: GitHub Actions Demo
-on: push
-jobs:
-  Example-Actions-Job:
-    name: Exploring GitHub Actions
-    runs-on: ubuntu-latest
-    steps:
-      # Display the event that triggered the workflow
-      - run: echo "The job was triggered by a ${{ github.event_name }} event."
-      
-      # Runner information
-      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub"
-      
-      # Information about the repository and branch
-      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
-      
-      # Use Action located in https://github.com/actions
-      - name: Check out repository code
-        uses: actions/checkout@v2  
-      
-      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
-      
-      - run: echo "Your repository has been copied to the path ${{ github.workspace }} on the runner."
-      
-      - run: echo "The workflow is now ready to test your code on the runner."
-      
-      - name: conditional step when event name is pull request
-        if: ${{ github.event_name == 'pull_request' }}
-        run: echo "This event is a pull request"
-      
-      - name: List files in the repository
-        run: |
-          ls ${{ github.workspace }}
-      
-      - name: Setup dotnet on runner
-        uses: actions/setup-dotnet@v1
-        with:
-          dotnet-version: '3.x'
-      
-      - name: Display dotnet version
-        run: dotnet --version
-      
-      - run: echo "The preinstalled tools are located here on the runner ${{ runner.tool_cache }}."
-      
-      - name: List files in tool cache
-        run: |
-          ls ${{ runner.tool_cache }}
-      
-      - run: echo "This job's status is ${{ job.status }}."
+name: Condition and Expression Demo
 
-  Second-Job:
-    name: The second job running on another runner
-    runs-on: windows-latest
-    needs: Example-Actions-Job
+on:
+  workflow_dispatch:
+    inputs:
+      failstep:
+        description: 'Fail step in Job1 (yes/no)'
+        required: true
+        default: 'no'
+
+jobs:
+  first-job:
+
+    runs-on: ubuntu-latest
+    
     steps:
-      - run: echo "This job is now running on a ${{ runner.os }} server hosted by GitHub."
+    
+      - name: checkout code if running on master branch
+        if: ${{ github.ref == 'refs/heads/master' }}
+        uses: actions/checkout@v2
+        
+      - name: YES was passed as workflow input
+        if: github.event.inputs.failstep == 'yes'
+        run: echo "Value passed by workflow_dispatch is YES to fail workflow." 
+
+      - name: NO was passed as workflow input
+        run: echo "Value passed by workflow_dispatch is NO to fail workflow." 
+        if: github.event.inputs.failstep == 'no'
+      
+      - name: Step that can be failed
+        env:
+          FAIL_STEP: ${{ github.event.inputs.failstep == 'yes' }}
+        run:  |
+          echo "This statement runs whether step exits 0 or 1"
+          if [[ $FAIL_STEP == true ]]
+          then
+            exit 1
+          fi
+
+      - name: Step in workflow
+        run: echo "Another step in the workflow" 
+
+      - name: This step only runs if there's a previous failure
+        if: failure()
+        run: echo "There has been a failure.  Perhaps send a notification." 
+
+      - name: Step in workflow
+        run: echo "Another step in the workflow" 
+          
+      - name: Step that always runs
+        if: always()
+        run:  echo "This step runs regardless of success or failure." 
+          
+      - name: Step that only runs on success of all steps
+        if: success()
+        run:  echo "This step only runs when no previous steps have failed." 
+
+  second-job:
+  
+    runs-on: ubuntu-latest
+    
+    needs: first-job
+    if: always()
+    steps:
+      - name: Sample step in job
+        run:  echo "Sample step output" 
